# Meta
name: "Alex Wilson"
description: "Random thoughts from a overly passionate developer."

# Links
base: "/"
baseurl: "/"
url: "https://ax.gy"
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
author: 
    name: Alex Wilson
    email: a@ax.gy
    uri: https://ax.gy/

# General
encoding: UTF-8

# Pagination
paginate: 5,
paginate_path: "/blog/:num"

# Collections
collections:
    projects:
        output: true
        permalink: /work/:path/
    about:
        output: true
        permalink: /about-me/:path/


# Sass
sass:
  style: compressed

# Gems
plugins:
    - jekyll-feed
    - jekyll-gist
    - jekyll-paginate
    - jekyll-sitemap

exclude:
    - node_modules
    - src
