# Meta
name: "Alex Wilson"
description: "Software Engineer, Technical Architect — Helping build a better, faster internet."

# Links
base: "/"
baseurl: "/"
url: "https://alexwilson.tech"
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
author: 
    name: Alex Wilson
    email: a@ax.gy
    uri: https://alexwilson.tech/

twitter:
    username: antoligy
    card: summary

social:
  name: Alex Wilson
  links:
    - https://twitter.com/antoligy
    - https://github.com/antoligy
    - https://www.linkedin.com/in/alex-/

# General
encoding: UTF-8

# Pagination
paginate: 5,
paginate_path: "/blog/:num"

# Collections
collections:
    projects:
        output: true
        permalink: /work/:path/
    about:
        output: true
        permalink: /about-me/:path/


# Sass
sass:
  style: compressed

# Gems
plugins:
    - jekyll-feed
    - jekyll-gist
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-seo-tag


exclude:
    - node_modules
    - src
