# Meta
name: "Alex Wilson"
description: "Need to think of something to go here..."

# Links
base: "/"
baseurl: "/"
url: "https://ax.gy"
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false

# General
encoding: UTF-8

# Pagination
paginate: 5,
paginate_path: "/blog/:num"

# Collections
collections:
    projects:
        output: true
        permalink: /work/:path/
    about:
        output: true
        permalink: /about-me/:path/


# Sass
sass:
  style: compressed

# Gems
gems:
    - jekyll-sitemap