# YAML variables
# Nested in one block so they can be removed at run-time.
__constants:
  time_format: &time_format "YYYY-MM-DDTHH:mm:ssZ"

backend:
  name: github
  repo: alexwilson/content
  branch: main
  base_url: https://alexwilson.tech/
  auth_endpoint: "auth/cms"
  use_graphql: true
  cms_label_prefix: status/

# We serialize this to JavaScript on deploys instead of dynamically fetching.
load_config_file: false

publish_mode: editorial_workflow

media_folder: pictures

display_url: https://alexwilson.tech/

collections:
  - name: "blog"
    label: "Blog"
    folder: "/posts/"
    create: true
    slug: "{{id}}"
    fields: &contentFields
      - {label: ID, name: id, required: true, widget: "uuid"}
      - {label: Title, name: "title", required: true, widget: "string"}
      - {label: Published Date, name: "date", required: true, format: *time_format, widget: "datetime"}
      - {label: Image, name: "image", required: false, widget: "image"}
      - {label: Tags, name: "tags", allow_add: true, label_singular: "Add", widget: "list"}
      - {label: Body, name: "body", widget: "markdown"}
      - {label: Content Type, name: "type", options: ["article", "talk"], default: "article", widget: "select"}
      - {label: "Author(s)", name: "author", widget: "select", options: ["alex"], default: "alex"}
      - {label: Updated Date, name: "last_modified_at", default: "", format: *time_format, required: false, widget: "datetime"}
  - name: "talks"
    label: "Talks"
    folder: "/talks/"
    create: true
    slug: "{{id}}"
    fields: *contentFields
