name: Automatically Update Dependencies
on: pull_request_target

jobs:
  auto-update-dependencies:
    name: approve and merge for dependency PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.PR_GH_TOKEN }}"
    - name: Enable Github Automerge
      uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: "${{ secrets.PR_GH_TOKEN }}"
