name: Automatically Update Dependencies
on: pull_request

jobs:
  auto-update-dependencies:
    name: approve and merge for dependency PRs
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        github-token: "${{ secrets.PR_GH_TOKEN }}"
    - name: Enable Github Automerge
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: "${{ secrets.PR_GH_TOKEN }}"
