on:
  push:
    # Respond to a push event on every brannch other than Github Pages.
    branches:
      - '!gh-pages'
      - '*'

  # Scheduled build so pipeline failures are noticed quicker.
  schedule:
    - cron: '30 4 * * 3,6'

name: Build, Test and Deploy
jobs:

  # Fetch dependencies and build Gatsby
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Restore Cached Build
      uses: actions/cache@v1
      id: cache-public
      with:
        path: public
        key: build
    - uses: actions/setup-node@master
    - name: Restore NPM Cache
      uses: actions/cache@v1
      id: cache-npm
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - name: Restore node_modules
      uses: actions/cache@v1
      id: cache-node_modules
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
      env:
        CI: true
    - name: Save Build Artefact
      uses: actions/upload-artifact@v1
      with:
        name: site-artefact
        path: public

  # Run unit tests on the artefact we just built.
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Download Website Artefact
      uses: actions/download-artifact@v1
      with:
        name: site-artefact
        path: public
    - uses: actions/setup-node@master
    - name: Restore NPM Cache
      uses: actions/cache@v1
      id: cache-npm
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - name: Restore node_modules
      uses: actions/cache@v1
      id: cache-node_modules
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test

  # Deploy to Github Pages environment
  deploy-production:
    name: Deploy to Production
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Download Website Artefact
      uses: actions/download-artifact@v1
      with:
        name: site-artefact
        path: public
    - name: Deploy to Github Pages
      uses: ./.github/actions/github-pages/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: public
    - name: Trigger a Pages Update
      run: |
        curl -sS -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_PAGES_DEPLOY_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/pages/builds \
