on:
  push:
    branches:
      - '!gh-pages'
      - '*'
name: Build and Deploy
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Restore Cached Dependencies
      uses: actions/cache@v1
      id: cache-node_modules
      with:
        path: node_modules
        key: ${{ hashFiles('package.json') }}
    - name: Restore Cached Build
      uses: actions/cache@v1
      id: cache-public
      with:
        path: public
        key: build
    - uses: actions/setup-node@master
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      uses: ./.github/actions/github-pages/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: public
    - name: Update Pages
      run: |
        curl -sS -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_PAGES_DEPLOY_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/pages/builds \
