on:
  push:
    branches:
      - '!gh-pages'
      - '*'
name: Build and Deploy
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: actions/cache@v1
      id: cache-node_modules
      with:
        path: node_modules
        key: ${{ hashFiles('package.json') }}
    - uses: actions/cache@v1
      id: cache-public
      with:
        path: public
        key: 'previous-build'
    - uses: actions/setup-node@master
    - run: npm install
    - run: npm run build
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      uses: ./.github/actions/github-pages/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: public
