name: Terraform Deployments

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy-to-test:
    concurrency:
      group: ${{ github.workflow }}-test
      cancel-in-progress: false
    runs-on: ubuntu-latest

    env:
      FASTLY_API_KEY: ${{ secrets.TERRAFORM_FASTLY_API_KEY }}
      TF_WORKSPACE: "test"

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

      - name: Set-up test workspace
        run: |
          terraform init

      - name: Apply test configuration
        run: terraform apply -auto-approve -var-file=environments/test.tfvars

      - name: Run tests against test
        run: |
          echo "Imagine these are real tests"

  deploy-to-prod:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    concurrency:
      group: ${{ github.workflow }}-prod
      cancel-in-progress: false
    runs-on: ubuntu-latest
    needs: deploy-to-test

    env:
      FASTLY_API_KEY: ${{ secrets.TERRAFORM_FASTLY_API_KEY }}
      TF_WORKSPACE: "prod"

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

      - name: Set-up prod workspace
        run: |
          terraform init

      - name: Apply prod configuration
        run: terraform apply -auto-approve -var-file=environments/prod.tfvars

      - name: Run tests against prod
        run: |
          echo "Imagine these are real tests"
