name: Terraform Deployments

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: "Lint Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Terraform Version
        id: tf_version
        run: echo "value=$(cat .terraform-version)" >> $GITHUB_OUTPUT
        working-directory: .
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.value }}
      - name: Lint Terraform
        run: terraform fmt -check

  lint-test-vcl:
    name: "Lint & Test VCL"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/modules/fastly/vcl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Falco
        run: brew install falco
      - name: Lint VCL
        run: falco lint -vv -I . main.vcl
      - name: Test VCL
        run: falco test -vv -I . main.vcl

  deploy-to-test:
    needs: [lint, lint-test-vcl]
    concurrency:
      group: ${{ github.workflow }}-test
      cancel-in-progress: false
    runs-on: ubuntu-latest

    env:
      FASTLY_API_KEY: ${{ secrets.TERRAFORM_FASTLY_API_KEY }}
      TF_WORKSPACE: "test"
      TF_LOG: "warn"

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Terraform Version
        id: tf_version
        run: echo "value=$(cat .terraform-version)" >> $GITHUB_OUTPUT
        working-directory: .
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.value }}
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

      - name: Set-up test workspace
        run: |
          terraform init

      - name: Apply test configuration
        run: terraform apply -auto-approve -var-file=environments/test.tfvars

      - name: Run tests against test
        run: |
          echo "Imagine these are real tests"

  deploy-to-prod:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    concurrency:
      group: ${{ github.workflow }}-prod
      cancel-in-progress: false
    runs-on: ubuntu-latest
    needs: deploy-to-test

    env:
      FASTLY_API_KEY: ${{ secrets.TERRAFORM_FASTLY_API_KEY }}
      TF_WORKSPACE: "prod"
      TF_LOG: "warn"

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Terraform Version
        id: tf_version
        run: echo "value=$(cat .terraform-version)" >> $GITHUB_OUTPUT
        working-directory: .
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.value }}
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

      - name: Set-up prod workspace
        run: |
          terraform init

      - name: Apply prod configuration
        run: terraform apply -auto-approve -var-file=environments/prod.tfvars

      - name: Run tests against prod
        run: |
          echo "Imagine these are real tests"
